export const OFFRES = [
  {
    id: '1',
    title: 'Vision d\'Exception',
    discount: '-30%',
    points: '60',
    coupons: 9,
    bgColor: '#e9c05a',
    imageUrl: 'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=800',
    logoUrl: 'https://cdn-icons-png.flaticon.com/128/2921/2921226.png',
    description: 'Une réduction exclusive sur toute la collection de lunettes de vue et de soleil.',
    conditions: 'Offre valable sur présentation du code QR en magasin.',
    expireDate: '2026-12-31',
    stock: 9,
    duree: '30 Jours',
  },
  {
    id: '2',
    title: 'Pc sur mesure',
    discount: '-5%',
    points: '100',
    coupons: 1,
    bgColor: '#751352',
    imageUrl: 'https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?w=800',
    logoUrl: 'https://cdn-icons-png.flaticon.com/128/3094/3094700.png',
    description: 'Bénéficiez de 5% de réduction sur la configuration de votre PC sur mesure.',
    conditions: 'Offre valable pour tout achat d\'une configuration complète.',
    expireDate: '2026-09-15',
    stock: 1,
    duree: '15 Jours',
  },
  {
    id: '3',
    title: 'Try to escape - Groupe de 4',
    discount: '-20DT',
    points: '45',
    coupons: 15,
    bgColor: '#787878',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800',
    logoUrl: 'https://cdn-icons-png.flaticon.com/128/2553/2553633.png',
    description: 'Vivez une aventure immersive en groupe de 4 personnes.',
    conditions: 'Réservation obligatoire par téléphone.',
    expireDate: '2026-10-01',
    stock: 15,
    duree: '20 Jours',
  },
  {
    id: '4',
    title: 'Yoga à deux',
    discount: '-50%',
    points: '80',
    coupons: 10,
    bgColor: '#d4b7a6',
    imageUrl: 'https://images.unsplash.com/photo-1552196563-55fdcde463ba?w=800',
    logoUrl: 'https://cdn-icons-png.flaticon.com/128/3132/3132049.png',
    description: 'Partagez un moment de détente avec notre offre Yoga à deux.',
    conditions: 'Valable pour les nouveaux abonnés uniquement.',
    expireDate: '2026-11-20',
    stock: 10,
    duree: '25 Jours',
  },
  {
    id: '5',
    title: 'Location Baby-Foot',
    discount: '-250DT',
    points: '200',
    coupons: 3,
    bgColor: '#7A8C7A',
    imageUrl: 'https://tse4.mm.bing.net/th/id/OIP.v64ZaRQ1wiSVqC-39t5gEwHaHa?rs=1&pid=ImgDetMain',
    logoUrl: 'https://tse2.mm.bing.net/th/id/OIP.ElQAwH0XKtj4raGKaQAxKwHaHa?rs=1&pid=ImgDetMain',
    description: 'Louez un baby-foot pour votre événement avec 250 DT de réduction.',
    conditions: 'Location minimum 4 heures. Livraison incluse à Tunis.',
    expireDate: '2026-08-30',
    stock: 3,
    duree: '10 Jours',
  },
  {
    id: '6',
    title: 'Flamingo Forest Parcours',
    discount: '-25%',
    points: '80',
    coupons: 5,
    bgColor: '#1a3c1a',
    imageUrl: 'https://images.unsplash.com/photo-1549421263-50452718e235?w=800',
    logoUrl: 'https://cdn-icons-png.flaticon.com/128/2921/2921226.png',
    description: 'Parcours aventure en forêt pour toute la famille.',
    conditions: 'Valable uniquement les mercredis après-midi.',
    expireDate: '2026-09-01',
    stock: 5,
    duree: '12 Jours',
  },
  {
    id: '1',
    title: "Vision d'Exception",
    discount: "-30%",
    points: "80",
    coupons: 9,
    bgColor: "#F59E0B",
    imageUrl: "https://tse1.mm.bing.net/th/id/OIP.drDY-zMaeQE5jZRwVnwjHwHaDt?rs=1&pid=ImgDetMain&o=7&rm=3",
    logoUrl: "https://png.pngtree.com/png-vector/20220625/ourmid/pngtree-glasses-symbol-illustration-design-png-image_5422990.png",
    description: "Profitez de 30% de réduction sur toute la collection de lunettes premium.",
    conditions: "Valable sur toutes les montures. Non cumulable avec d'autres offres.",
    expireDate: "2026-09-01",
    stock: 9,
    duree: "30 Jours",
  },
  {
    id: '2',
    title: "Pc sur mesure",
    discount: "-5%",
    points: "100",
    coupons: 5,
    bgColor: "#6B0530",
    imageUrl: "https://tse3.mm.bing.net/th/id/OIP.0L-PEvX0LRgQcsdW-K_VggHaGB?rs=1&pid=ImgDetMain&o=7&rm=3",
    logoUrl: "https://img.freepik.com/vecteurs-premium/creation-logo-icone-ordinateur-pc_775854-1632.jpg",
    description: "Configurez votre PC sur mesure avec 5% de réduction.",
    conditions: "Valable sur les configurations personnalisées uniquement.",
    expireDate: "2026-08-15",
    stock: 5,
    duree: "15 Jours",
  },
  {
    id: '3',
    title: "Try to escape",
    discount: "-20DT",
    points: "40",
    coupons: 12,
    bgColor: "#A68980",
    imageUrl: "https://cdn.akamai.steamstatic.com/steam/apps/2506760/header.jpg?t=1697803659",
    logoUrl: "https://via.placeholder.com/50/A68980/ffffff?text=TE",
    description: "Vivez une expérience unique d'escape game avec 20 DT de réduction.",
    conditions: "Valable pour 2 personnes minimum. Sur réservation uniquement.",
    expireDate: "2026-10-01",
    stock: 12,
    duree: "45 Jours",
  },
  {
    id: '4',
    title: "Yoga à deux",
    discount: "-50%",
    points: "80",
    coupons: 15,
    bgColor: "#D4B499",
    imageUrl: "https://tse4.mm.bing.net/th/id/OIP.0gjbjJ55VEOZPcrT2n5shQHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    logoUrl: "https://tse1.mm.bing.net/th/id/OIP.IrR9fFwRze0_dx4BwqQWVAHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "Partagez une séance de yoga en duo avec 50% de réduction.",
    conditions: "Valable pour 2 personnes. Sur réservation 24h à l'avance.",
    expireDate: "2026-09-15",
    stock: 15,
    duree: "25 Jours",
  },
  {
    id: '5',
    title: "Location Baby-Foot",
    discount: "-250DT",
    points: "200",
    coupons: 3,
    bgColor: "#7A8C7A",
    imageUrl: "https://tse4.mm.bing.net/th/id/OIP.v64ZaRQ1wiSVqC-39t5gEwHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    logoUrl: "https://tse2.mm.bing.net/th/id/OIP.ElQAwH0XKtj4raGKaQAxKwHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "Louez un baby-foot pour votre événement avec 250 DT de réduction.",
    conditions: "Location minimum 4 heures. Livraison incluse à Tunis.",
    expireDate: "2026-08-30",
    stock: 3,
    duree: "10 Jours",
  },
  {
    id: '4',
    title: "Yoga à deux",
    discount: "-50%",
    points: "80",
    coupons: 15,
    bgColor: "#D4B499",
    imageUrl: "https://tse4.mm.bing.net/th/id/OIP.0gjbjJ55VEOZPcrT2n5shQHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    logoUrl: "https://tse1.mm.bing.net/th/id/OIP.IrR9fFwRze0_dx4BwqQWVAHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "Partagez une séance de yoga en duo avec 50% de réduction.",
    conditions: "Valable pour 2 personnes. Sur réservation 24h à l'avance.",
    expireDate: "2026-09-15",
    stock: 15,
    duree: "25 Jours",
  },
  {
    id: '6',
    title: "",
    discount: "-250DT",
    points: "200",
    coupons: 3,
    bgColor: "#7A8C7A",
    imageUrl: "https://tse4.mm.bing.net/th/id/OIP.v64ZaRQ1wiSVqC-39t5gEwHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    logoUrl: "https://tse2.mm.bing.net/th/id/OIP.ElQAwH0XKtj4raGKaQAxKwHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    description: "Louez un baby-foot pour votre événement avec 250 DT de réduction.",
    conditions: "Location minimum 4 heures. Livraison incluse à Tunis.",
    expireDate: "2026-08-30",
    stock: 3,
    duree: "10 Jours",
  },
];